/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jonesx_videoplayer_VideoPlayer */

#ifndef _Included_com_oseasy_mmc_localaudiorender_AudioRender
#define _Included_com_oseasy_mmc_localaudiorender_AudioRender
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jonesx_videoplayer_VideoPlayer
 * Method:    play
 * Signature: (Ljava/lang/Object;)I
 */

JNIEXPORT void JNICALL Java_com_oseasy_mmc_localaudiorender_AudioRender_NetStart
        (JNIEnv *, jclass,jstring,jint,jint);

JNIEXPORT jbyteArray JNICALL Java_com_oseasy_mmc_localaudiorender_AudioRender_GetAACFrame
        (JNIEnv*,jclass);

#ifdef __cplusplus
}
#endif

#endif