/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#ifndef _Included_com_oseasy_mmc_multiclient_CORE
#define _Included_com_oseasy_mmc_multiclient_CORE
#ifdef __cplusplus
extern "C" {
#endif
JNIEXPORT void JNICALL Java_com_oseasy_mmc_multiclient_Core_Start
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif

#endif