/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#ifndef _Included_com_oseasy_mmc_multiclientyh_MultiClient
#define _Included_com_oseasy_mmc_multiclientyh_MultiClient
#ifdef __cplusplus
extern "C" {
#endif
JNIEXPORT void JNICALL Java_com_oseasy_mmc_multiclient_MultiClient_Start
        (JNIEnv *, jobject,jstring,jstring,jstring);

#ifdef __cplusplus
}
#endif

#endif